profile=high-quality
hwdec-codecs=mpeg1video,mpeg2video,mpeg4,vc1,vp8,vp9,h264,hevc,av1
hwdec=auto-safe
gpu-api=vulkan
vo=gpu-next

title=${filename} - ${mpv-version}
image-display-duration=inf
no-taskbar-progress
cursor-autohide=500
keep-open=always
autofit=75%x75%
volume-max=100
sub-gray
pause
idle

osd-on-seek=msg
osd-border-size=2
osd-font-size=18
osd-margin-x=20
osd-margin-y=16
osd-blur=2
no-osd-bar

scale=ewa_hanning
scale-antiring=0.5
dscale=gaussian
dscale-param1=0.5625

target-colorspace-hint
dither-depth=8  # https://github.com/mpv-player/mpv/issues/11862

no-deband
deband-iterations=16
deband-grain=48

sub-auto=fuzzy
audio-file-auto=fuzzy

screenshot-format=png
screenshot-dir="~~/screenshots"
screenshot-template="%f-%wH.%wM.%wS.%wT-#%#00n"

[autoloop]
profile-cond=duration > 0 and duration <= 30
profile-restore=copy
loop

[subsplease]
profile-cond=string.match(p.filename, "SubsPlease")
profile-restore=copy
deband

[benchmark]
profile-restore=copy
osd-msg1="FPS: ${estimated-display-fps}"
video-sync=display-desync
vulkan-swap-mode=immediate
opengl-swapinterval=0
d3d11-sync-interval=0
no-audio
untimed