profile=high-quality
vo=gpu-next

image-display-duration=inf
no-taskbar-progress
autofit=90%x90%
volume-max=100
keep-open
pause
idle

osd-border-size=2
osd-font-size=18
osd-margin-x=20
osd-margin-y=16
osd-on-seek=msg
no-osd-bar

scale-antiring=0.6
dscale=mitchell

# target-colorspace-hint
dither-depth=8  # https://github.com/mpv-player/mpv/issues/11862

no-deband
deband-iterations=4

screenshot-format=png
screenshot-dir="~~/screenshots"
screenshot-template="%f-%wH.%wM.%wS.%wT-#%#00n"

[autoloop]
profile-cond=duration > 0 and duration <= 30
profile-restore=copy
loop

[subsplease]
profile-cond=filename:match("SubsPlease")
profile-restore=copy
deband

[benchmark]
profile-restore=copy
osd-msg1="FPS: ${estimated-display-fps}"
video-sync=display-desync
vulkan-swap-mode=immediate
opengl-swapinterval=0
d3d11-sync-interval=0
no-audio
untimed